# Generated by Django 4.2 on 2023-04-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_adventure_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='published',
        ),
    ]
